.TH SDLTABLE 1 "2011-04-27" "VERSION"
.SH NAME
sdltable \- <short project description>
.SH SYNOPSIS
.B sdltable
.SH DESCRIPTION
.B sdltable
is the next big thing.
.P
.B sdltable
solves all your problems.
.SH OPTIONS
.B sdltable
has no options.
.SH USAGE
.SS General use
.TP
Use it wisely.
.SH BUGS
.B sdltable
has no known bugs.
.TP
If you find any bugs, please send them to <mastensg@ping.uio.no>.
.SH AUTHOR
Martin Stensgård <mastensg@ping.uio.no>
.SH SEE ALSO
.BR man (1),
